#!/usr/bin/env python3.12
"""Build Geant4 XY position-scan macros for TiO2 and Vikuiti variants."""

from __future__ import annotations

import argparse
from pathlib import Path


def frange(start: float, stop: float, step: float) -> list[float]:
    values = []
    value = start
    eps = abs(step) * 1e-9
    while value <= stop + eps:
        values.append(round(value, 10))
        value += step
    return values


def macro_text(
    variant_name: str,
    root_path: Path,
    xs: list[float],
    ys: list[float],
    events_per_point: int,
) -> str:
    lines = [
        f"# Position scan for {variant_name}. Generated by build_position_scan_macros.py",
        "/control/verbose 1",
        "/run/verbose 1",
        "/event/verbose 0",
        "/tracking/verbose 0",
        f"/analysis/setFileName {root_path}",
        f"/hodoscope/setDetectorVariant {variant_name}",
        "/hodoscope/det/optical true",
        "/hodoscope/det/improvedOptical true",
        "/hodoscope/det/setD 5.0 mm",
        "/run/initialize",
        "/gun/particle mu-",
        "/gun/energy 4.0 GeV",
        "/gun/direction 0.0 0.0 -1.0",
        "",
    ]
    for y in ys:
        for x in xs:
            lines.append(f"/gun/position {x:.6g} {y:.6g} 50.0 mm")
            lines.append(f"/run/beamOn {events_per_point}")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--events-per-point", type=int, default=20)
    parser.add_argument("--xmin", type=float, default=-16.0)
    parser.add_argument("--xmax", type=float, default=16.0)
    parser.add_argument("--dx", type=float, default=1.0)
    parser.add_argument("--ymin", type=float, default=-16.0)
    parser.add_argument("--ymax", type=float, default=16.0)
    parser.add_argument("--dy", type=float, default=1.0)
    parser.add_argument(
        "--outdir",
        type=Path,
        default=Path("diagnostics/instrument_response/macros"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)
    xs = frange(args.xmin, args.xmax, args.dx)
    ys = frange(args.ymin, args.ymax, args.dy)

    outputs = {
        "tio2": ("Hod2019", Path("diagnostics/instrument_response/outputs/position_scan_tio2.root")),
        "vikuiti": ("Hod2018", Path("diagnostics/instrument_response/outputs/position_scan_vikuiti.root")),
    }
    for tag, (variant, root_path) in outputs.items():
        path = args.outdir / f"position_scan_{tag}.mac"
        path.write_text(
            macro_text(variant, root_path, xs, ys, args.events_per_point),
            encoding="utf-8",
        )
        print(
            f"Wrote {path} with {len(xs)} x {len(ys)} points, "
            f"{args.events_per_point} events/point"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
