#!/usr/bin/env python3
import sys, os
import json

outdir = sys.argv[1] if len(sys.argv)>1 else 'outputs'
tables = os.path.join(outdir, 'tables')
root = os.path.join(outdir, 'root')
report = 'ITERATION1_OPTICAL_VALIDATION_SUMMARY.md'

with open(report, 'w') as fo:
    fo.write('# Iteration 1 Optical Validation Summary\n\n')
    fo.write('Autogenerated summary. See tables/ and logs/.\n\n')
    if os.path.isdir(tables):
        fo.write('## Tables present\n')
        for f in os.listdir(tables):
            fo.write(f'- {f}\n')
    fo.write('\n')
    fo.write('Run completed. Check outputs/logs for details.\n')
